### PR TITLE
Benchmarks: feature fixes

### LINKED ISSUE #2181: Benchmarks Issues
Came across some issues with how we are running benchmarks with @enddynayn 

1. The `frequency-bench` chain is enabled for the `frequency` feature, but should only be enabled for `runtime-benchmarks` feature
2. When we are running the benchmarks in `run_benchmarks.sh` it is running with `features=runtime-benchmarks,frequency-lint-check`. Should it instead be running with `features=runtime-benchmarks,frequency`?
    - Would this cause issues with non-mainnet pallets?
    - Perhaps it should run this way for release only?
3. `node/service/src/chain_spec/frequency.rs` `benchmark_mainnet_config` should be limited to the `runtime-benchmarks` feature

### PR DESCRIPTION
**Pull request by aramikm**
# Goal
The goal of this PR is to dome some feature fixes

Closes #2181 

# Discussion

- the point number 2 did not work after trying with following error
`...
Error: Input("The runtime returned an error when trying to build the genesis storage. Please ensure that all pallets define a genesis config that can be built. This can be tested with: https://github.com/paritytech/polkadot-sdk/pull/3412\nError: Invalid JSON blob: unknown field `sudo`, expected one of `system`, `parachainSystem`, `parachainInfo`, `democracy`, `balances`, `council`, `technicalCommittee`, `treasury`, `collatorSelection`, `session`, `aura`, `auraExt`, `timeRelease`, `schemas` at line 171 column 8 for blob:
...`

# Checklist
- [x] Benchmarks added?
- [x] Runtime spec change

### CODE REVIEW

File: pallets/capacity/src/weights.rs [hunk 1]
```diff
@@ -280,32 +266,19 @@ impl WeightInfo for () {
...
 			.saturating_add(RocksDbWeight::get().writes(1_u64))
 	}
 	/// Storage: `Capacity::ProviderBoostHistories` (r:1 w:1)
 	/// Proof: `Capacity::ProviderBoostHistories` (`max_values`: None, `max_size`: Some(641), added: 3116, mode: `MaxEncodedLen`)
 	/// Storage: `Capacity::StakingAccountLedger` (r:1 w:1)
 	/// Proof: `Capacity::StakingAccountLedger` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
-	/// Storage: `Capacity::StakingRewardPool` (r:1 w:1)
-	/// Proof: `Capacity::StakingRewardPool` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
+	/// Storage: `Capacity::CurrentEraProviderBoostTotal` (r:1 w:1)
+	/// Proof: `Capacity::CurrentEraProviderBoostTotal` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
```
Comment (aramikm) [inline pallets/capacity/src/weights.rs:281]: @shannonwells would you mind take a look at these changes?

File: pallets/capacity/src/weights.rs [hunk 2]
```diff
@@ -314,21 +287,21 @@ impl WeightInfo for () {
...
-		// Minimum execution time: 23_903_000 picoseconds.
-		Weight::from_parts(24_664_000, 4081)
-			.saturating_add(RocksDbWeight::get().reads(4_u64))
-			.saturating_add(RocksDbWeight::get().writes(4_u64))
+		//  Measured:  `359`
+		//  Estimated: `4601`
+		// Minimum execution time: 34_128_000 picoseconds.
+		Weight::from_parts(34_952_000, 4601)
+			.saturating_add(RocksDbWeight::get().reads(6_u64))
+			.saturating_add(RocksDbWeight::get().writes(6_u64))
```
Comment (aramikm) [inline pallets/capacity/src/weights.rs:295]: same here?

**Review by mattheworris — APPROVED** [review]
- Read through changes (quickly skimmed weights)
🚢 it!

**Review by JoeCap08055 — APPROVED** [review]
Weight updates look reasonable to me

File: node/cli/src/command.rs [hunk 3]
```diff
@@ -65,7 +65,7 @@ impl<T: sc_service::ChainSpec + 'static> IdentifyChain for T {
 
 fn load_spec(id: &str) -> std::result::Result<Box<dyn ChainSpec>, String> {
 	match id {
-		#[cfg(feature = "frequency")]
+		#[cfg(feature = "runtime-benchmarks")]
```
Comment (enddynayn) [inline node/cli/src/command.rs:68]: 👍

**Review by enddynayn — APPROVED** [review]
👍 great!

File: pallets/capacity/src/weights.rs (hunk 1 above)
Comment (shannonwells) [reply pallets/capacity/src/weights.rs:281]: The diff is a little weird, so I checked out the branch, it looks right.

File: pallets/capacity/src/weights.rs (hunk 2 above)
Comment (shannonwells) [reply pallets/capacity/src/weights.rs:295]: It looks right here too.

**Review by shannonwells — APPROVED** [review]
I checked out the branch and compared the provider boost related weight calculations with what they were before, and also looked at the functions themselves to ensure they were they way I expected.
