### PR TITLE
Bug Fix: Schema Runtime API typo

### LINKED ISSUE #2054: [Bug]: Exported method SchemasRuntimeApi_get_schema_by_id is not found
### What happened?

The runtime call for getting a schema by id is failing in Polkadotjs/app:

image

Note that the Custom RPC for this still works, which is odd as it should be using that same RuntimeAPI.

### Relevant log output

```shell
schemasRuntimeApi.getSchemaById: Option<SchemaResponse>
-32000: Client error: Execution failed: Other: Exported method SchemasRuntimeApi_get_schema_by_id is not found
```

### PR DESCRIPTION
**Pull request by wilwade**
# Goal
The goal of this PR is to fix a typo in API Augment

Closes #2054

# Discussion

- Just a typo in API Augment in the Runtime API interface
- Updated js dependencies as well

# Testing

Not simple, but if you want to you have to:
- Pull branch
- Build api-augment: `make js`
- Pull the polkadotjs/apps
- Manually install frequency api-augment build and run
- Test that you can now call get_by_schema_id from the Runtime API interface

### CODE REVIEW

File: js/api-augment/definitions/schemas.ts [hunk 1]
```diff
@@ -66,7 +66,7 @@ export default {
     SchemasRuntimeApi: [
       {
         methods: {
-          get_schema_by_id: {
+          get_by_schema_id: {
```
Comment (wilwade) [inline js/api-augment/definitions/schemas.ts:69]: 👋 Over here! 👋 

This is the actual fix!

Comment (saraswatpuneet) [reply js/api-augment/definitions/schemas.ts:69]: 🧑🏽‍🔧

**Review by saraswatpuneet — APPROVED** [review]

**Review by mattheworris — APPROVED** [review]

**Review by shannonwells — CHANGES_REQUESTED** [review]
I'm not sure about this change.  Why do we have both get_schema_by_id and get_by_schema_id all over the code?  They appear to be returning the same thing.  I find it confusing.

**Comment by wilwade** [comment]
@shannonwells 
> I'm not sure about this change. Why do we have both get_schema_by_id and get_by_schema_id all over the code? They appear to be returning the same thing. I find it confusing.

It is confusing. I believe this is due to a few things:

1. `get_by_schema_id` in the Messages pallet/rpcs for getting messages by Schema Id.
2. `get_by_schema_id` in the Schemas pallet is to get the schema, by id.
3. `get_schema_by_id` is also in the messages pallet rpc to allow the messages RPCs to be able to get schema information without having a cross dependency (the link is at the runtime instead)

Not sure what we want to do to fix the confusion, but this fixes the current bug.

**Review by shannonwells — APPROVED** [review]
Ok that answered my question thanks
