### PR TITLE
stateful-storage: check hash in signed extension

### LINKED ISSUE #1860: `target_hash` RPC Level validation
As someone transacting using stateful storage, I want to have my transaction stopped at the node level if I submit something with a bad `target_hash` so that I don't waste capacity on a transaction that will fail.

## Scenario
- User has two providers, A and B
- User is actively using both A and B
- User makes a change on A and a change on B that both effect the same stateful store
- Provider A makes the change
- Provider B uses the cached value from before the change by A
- The changes are in a race condition
- Provider B would like to safely use the cached value without fear of an invalid hash using capacity

## Checklist
- [ ] Make sure the pallet benchmarks are correct
- [ ] Make sure the overhead benchmarks are correct

## Questions
- Should this validation run on `pre_dispatch` as well as `validate`?
    - **A**: We want to do both 
    - If `pre_dispatch` and `validate`, we should remove the check in the extrinsic
    - If just `validate`, we cannot remove the extrinsic check, but also no weights etc...
- Should other checks also be moved into the signed extrinsics?
    - Just the one check for the hash

Draft PR: https://github.com/LibertyDSNP/frequency/pull/1288

### PR DESCRIPTION
**Pull request by aramikm**
# Goal
The goal of this PR is to check the hash for stateful storage transactions and fail early.

Closes #1860

# Checklist
- [x] e2e Tests added?
- [X] Benchmarks added?
- [x] Spec version incremented?

### CODE REVIEW

File: pallets/stateful-storage/src/signed_extension.rs [hunk 1]
```diff
@@ -0,0 +1,200 @@
...
+use scale_info::TypeInfo;
+use sp_runtime::{
+	traits::{DispatchInfoOf, Dispatchable, SignedExtension},
+	transaction_validity::{InvalidTransaction, TransactionValidity, TransactionValidityError},
+	DispatchError,
+};
+
+/// The SignedExtension trait is implemented on CheckFreeExtrinsicUse to validate the request. The
+/// purpose of this is to ensure that the target_hash is verified in transaction pool before getting
+/// into block. This is to reduce the chance that capacity consumption due to stale hash
```
Comment (shannonwells) [inline pallets/stateful-storage/src/signed_extension.rs:21]: nit. only if you are already going to change something in this file
```suggestion
/// into block. This is to reduce the chance of capacity consumption due to stale hash
```

File: pallets/stateful-storage/src/signed_extension.rs [hunk 2]
```diff
@@ -0,0 +1,200 @@
...
+		_call: &Self::Call,
+		_info: &DispatchInfoOf<Self::Call>,
+		_len: usize,
+	) -> Result<Self::Pre, TransactionValidityError> {
+		// Since we already check the hash in stateful-storage-pallet extrinsics we do not need to
+		// check the hash before dispatching
+		Ok(())
+	}
+
+	/// Filters stateful extrinsics and verifies the hashes to ensure we are proceeding
```
Comment (shannonwells) [inline pallets/stateful-storage/src/signed_extension.rs:131]: not?
```suggestion
	/// Filters stateful extrinsics and verifies the hashes to ensure we are not proceeding
```

**Review by shannonwells — APPROVED** [review]
Only a couple of little things for comments, not worth doing a CI round trip unless you are already going to change those files.

File: pallets/stateful-storage/src/signed_extension.rs [hunk 3]
```diff
@@ -0,0 +1,200 @@
...
+				Self::verify_hash_paginated(
+					&state_owner_msa_id,
+					&payload.schema_id,
+					&payload.page_id,
+					&payload.target_hash,
+				)
+			},
+			_ => Ok(Default::default()),
+		}
+	}
```
Comment (saraswatpuneet) [inline pallets/stateful-storage/src/signed_extension.rs:199]: nit: can this match block be further refactored?

**Review by saraswatpuneet — DISMISSED** [review]
Read through, looks good

Do we need to update any weights  (overhead) ?

File: pallets/stateful-storage/src/tests/signed_extension_tests.rs [hunk 4]
```diff
@@ -0,0 +1,191 @@
...
+			msa_id,
+			paginated_schema_id,
+			0,
+			prev_content_hash,
+			BoundedVec::try_from(payload.clone()).unwrap(),
+		));
+		let calls: Vec<<Test as frame_system::Config>::RuntimeCall> = vec![
+			RuntimeCall::StatefulStoragePallet(Call::apply_item_actions {
+				actions: BoundedVec::try_from(actions.clone()).unwrap(),
+				target_hash: NONEXISTENT_PAGE_HASH,
```
Comment (JoeCap08055) [inline pallets/stateful-storage/src/tests/signed_extension_tests.rs:53]: maybe a nit, but I feel like using `NONEXISTENT_PAGE_HASH` (== 0) in the tests is a bit too simple; it feels like it has the potential to hit a special case in the code under test (I'm pretty sure it doesn't, but it feels weird to me anyway). Maybe better to use a random number? (Or test both cases: 0 and <random number>?)

File: pallets/stateful-storage/src/signed_extension.rs [hunk 5]
```diff
@@ -0,0 +1,200 @@
...
+		if let Ok(Some(page)) = Pallet::<T>::get_itemized_page_for(*msa_id, *schema_id) {
+			let current_hash: PageHash = page.get_hash();
+
+			ensure!(
+				&current_hash == target_hash,
+				map_dispatch_error(Error::<T>::StalePageState.into())
+			);
+
+			return ValidTransaction::with_tag_prefix(TAG_PREFIX)
+				.and_provides((msa_id, schema_id))
```
Comment (enddynayn) [inline pallets/stateful-storage/src/signed_extension.rs:49]: 👍

File: pallets/stateful-storage/src/signed_extension.rs [hunk 6]
```diff
@@ -0,0 +1,200 @@
...
+		if let Ok(Some(page)) = Pallet::<T>::get_paginated_page_for(*msa_id, *schema_id, *page_id) {
+			let current_hash: PageHash = page.get_hash();
+
+			ensure!(
+				&current_hash == target_hash,
+				map_dispatch_error(Error::<T>::StalePageState.into())
+			);
+
+			return ValidTransaction::with_tag_prefix(TAG_PREFIX)
+				.and_provides((msa_id, schema_id, page_id))
```
Comment (enddynayn) [inline pallets/stateful-storage/src/signed_extension.rs:72]: 👍

File: pallets/stateful-storage/src/signed_extension.rs [hunk 7]
```diff
@@ -0,0 +1,200 @@
...
+		write!(f, "StatefulStorageSignedExtension<{:?}>", self.0)
+	}
+	#[cfg(not(feature = "std"))]
+	fn fmt(&self, _: &mut sp_std::fmt::Formatter) -> sp_std::fmt::Result {
+		Ok(())
+	}
+}
+
+/// Map a module DispatchError to an InvalidTransaction::Custom error
+pub fn map_dispatch_error(err: DispatchError) -> InvalidTransaction {
```
Comment (enddynayn) [inline pallets/stateful-storage/src/signed_extension.rs:92]: fancy

File: pallets/stateful-storage/src/signed_extension.rs [hunk 8]
```diff
@@ -0,0 +1,200 @@
...
+	InvalidTransaction::Custom(match err {
+		DispatchError::Module(module_err) =>
+			<u32 as Decode>::decode(&mut module_err.error.as_slice())
+				.unwrap_or_default()
+				.try_into()
+				.unwrap_or_default(),
+		_ => 255u8,
```
Comment (enddynayn) [inline pallets/stateful-storage/src/signed_extension.rs:99]: It looks like we might end up with an error code that isn’t entirely accurate. Same in matching case - zero.

**Review by enddynayn — APPROVED** [review]
👍 great!

File: pallets/stateful-storage/src/signed_extension.rs (hunk 8 above)
Comment (JoeCap08055) [reply pallets/stateful-storage/src/signed_extension.rs:99]: Also, just a note: the "Custom Error" code that we get as part of the RPC "1010" error is entirely arbitrary, and does not indicate the pallet. So a code of `9` (StalePageHash) is not meaningful to the end user, because they don't know what pallet enum that comes from. I do think somewhere there is an enum of custom RPC error codes for Frequency; perhaps we should map to that instead? Sadly Polkadot/Substrate does not give us a way to propagate anything more than an integer value for custom RPC errors.

File: pallets/stateful-storage/src/tests/signed_extension_tests.rs (hunk 4 above)
Comment (aramikm) [reply pallets/stateful-storage/src/tests/signed_extension_tests.rs]: Changing to a random value on any run would create a flaky test with very low priority of failure but still using a deterministic stale value would be better. I'll use a different hash variable name to make it less confusing.

**Comment by aramikm** [comment]
> Read through, looks good
> 
> Do we need to update any weights (overhead) ?

I calculated the overhead benchmark and it didn't change. My guess is that since we don't have anything inside `pre_dispatch` it didn't add to overhead.

File: pallets/stateful-storage/src/signed_extension.rs [hunk 9]
```diff
@@ -0,0 +1,200 @@
...
+			Some(Call::delete_page {
+				state_owner_msa_id, schema_id, target_hash, page_id, ..
+			}) => Self::verify_hash_paginated(state_owner_msa_id, schema_id, page_id, target_hash),
+			Some(Call::apply_item_actions_with_signature { payload, .. }) =>
+				Self::verify_hash_itemized(
+					&payload.msa_id,
+					&payload.schema_id,
+					&payload.target_hash,
+				),
+			Some(Call::upsert_page_with_signature { payload, .. }) => Self::verify_hash_paginated(
```
[the remark this answers is not in the document]
Comment (enddynayn) [reply pallets/stateful-storage/src/signed_extension.rs:156]: That helps. I suggest doing it only if you need to run the build again,.

File: pallets/stateful-storage/src/signed_extension.rs (hunk 8 above)
Comment (enddynayn) [reply pallets/stateful-storage/src/signed_extension.rs:99]: Interesting approach but works.

Comment (JoeCap08055) [reply pallets/stateful-storage/src/signed_extension.rs:99]: Probably a wider issue than this PR, but the universal enum idea might not be so bad; we wouldn't need to map every error from every pallet; only the ones that can happen in a SignedExtension check. There shouldn't be that many.

Anyway, this approach works for now; maybe it's worth a backlog issue to revisit how we do this across all of our signed extensions, or maybe not.

**Review by JoeCap08055 — APPROVED** [review]

File: runtime/frequency/src/lib.rs [hunk 10]
```diff
@@ -1235,6 +1249,279 @@ construct_runtime!(
...
+	fn fmt(&self, f: &mut sp_std::fmt::Formatter) -> sp_std::fmt::Result {
+		write!(f, "StaleHashCheckExtension")
+	}
+	#[cfg(not(feature = "std"))]
+	fn fmt(&self, _: &mut sp_std::fmt::Formatter) -> sp_std::fmt::Result {
+		Ok(())
+	}
+}
+
+impl SignedExtension for StaleHashCheckExtension {
```
Comment (aramikm) [inline runtime/frequency/src/lib.rs:1296]: had to bring it out of pallet and inside runtime to be able to support multiple pallets and instead of using generics which was causing issues when used for multiple pallets it's directly using the concrete type used in the runtime

Comment (enddynayn) [reply runtime/frequency/src/lib.rs:1296]: Could we have used a similar approach to how we inject CapacityEligibleCalls into the frequency-tx-payment pallet and injected a struct that includes the extract_hash_data function?

File: runtime/frequency/src/lib.rs [hunk 11]
```diff
@@ -1235,6 +1249,279 @@ construct_runtime!(
...
+				)],
+				_ => vec![],
+			},
+			RuntimeCall::FrequencyTxPayment(FrequencyPaymentCall::pay_with_capacity {
+				call,
+				..
+			}) => Self::extract_hash_data(call),
+			RuntimeCall::FrequencyTxPayment(
+				FrequencyPaymentCall::pay_with_capacity_batch_all { calls, .. },
+			) => calls.iter().flat_map(|c| Self::extract_hash_data(c)).collect(),
```
Comment (enddynayn) [inline runtime/frequency/src/lib.rs:1452]: 👍

**Review by enddynayn — APPROVED** [review]
Great! 👍  I also suggest adding some unit tests to the signed extension.

File: runtime/frequency/src/lib.rs (hunk 11 above)
Comment (JoeCap08055) [reply runtime/frequency/src/lib.rs:1452]: Nice! I like this refactor.

**Review by JoeCap08055 — APPROVED** [review]
Nice rework.
- Pulled & built branch
- Ran unit tests
- Ran e2e tests

Looks good!

**Review by shannonwells — APPROVED** [review]
Looks good to me.  I think it's good to go and if it can be done the same way as CapacityEligibleCalls I think it can be revisited later.

File: runtime/frequency/src/lib.rs (hunk 10 above)
Comment (aramikm) [reply runtime/frequency/src/lib.rs:1296]: I think I can make that work. I'll close and merge this and add an issue for that

**Comment by aramikm** [comment]
Refactor issue is created https://github.com/frequency-chain/frequency/issues/2145
