### PR TITLE
added migrations for key fix

### LINKED ISSUE #2227: [Bug]: Fix the key issues
### What happened?

Currently some of the keys imported into the chain don't have the correct Avro prefix. We need to fix these keys.

The fix is prefixing all stored itemized storage items on schema_id `7` with `0x40`

# Affected Msa Accounts

## testnet 
```
8004, 8009, 8816, 8817, 8818, 8819, 8820, 8822, 8823, 8824, 8825, 8826, 9384, 9753, 9919,
9992, 9994, 9996, 9997, 10009, 10010, 10012, 10013, 10014, 10015, 10019, 10020, 10021,
10022, 10023, 10024, 10025, 10026, 10027, 10028, 10029, 10030, 10031, 10032, 10033, 10034,
10035, 10036, 10037, 10038, 10039, 10040, 10041, 10042, 10043, 10044, 10045, 10046, 10047,
10048, 10049, 10050, 10051, 10052, 10053, 10054, 10055, 10056, 10057, 10058, 10059, 10061,
10062, 10064, 10067, 10068, 10069, 10070, 10071, 10072, 10075, 10076, 10077, 10078, 10079,
10138, 10139, 10140, 10206, 10207, 10209, 10212, 10218, 10219, 10220, 10221, 10222, 10223,
10224, 10231, 10232, 10233, 10234, 10235, 10236, 10237, 10238, 10239, 10240, 10241, 10242,
10243, 10247, 10248, 10251, 10253, 10254, 10255, 10256, 10257, 10258, 10259, 10260, 10261,
10262, 10263, 10264, 10265, 10266, 10267, 10268, 10269, 10270, 10271, 10272, 10273, 10274,
10275, 10287, 10288, 10289, 10290, 10291, 10292, 10293, 10294, 10295, 10296, 10297, 10298,
10299, 10300, 10301, 10302, 10303, 10304, 10305, 10306, 10307, 10308, 10309, 10311, 10312,
10313, 10314, 10315, 10316, 10317, 10318, 10319, 10320, 10321, 10322, 10323, 10324, 10325,
10326, 10327, 10328, 10329,
```
- [x] Done
## mainnet

```
227, 542, 1249820, 1287729, 1288925, 1309067, 1309241, 1309258, 1309367, 1309397,
1329112, 1329535, 1330067,
```
- [x] Done

### PR DESCRIPTION
**Pull request by aramikm**
# Goal
The goal of this PR is 

Closes #2227

# Details
- The mainnet will be migrated as all other migrations since it is small enough that would easily fit into a block via 
```rust
pallet_stateful_storage::migration::v1::MigrateToV1<Runtime>
```
- For testnet we will use the same path as block just to mark the
```rust
Pallet::<T>::on_chain_storage_version();
```
but the actual multi-block migration is using `on_initialize` hook and a new storage item called `MigrationPageIndex` that would store the progress. 

# Verification
- There are issues with try-runtime that doesn't allow me to run it against mainnet or testnet. Added some tests to verify the changes.

# Checklist
- [x] Unit Tests added?
- [x] Spec version incremented?

### CODE REVIEW

File: pallets/stateful-storage/src/migration/v1.rs [hunk 1]
```diff
@@ -0,0 +1,258 @@
...
+				log::warn!(target: LOG_TARGET, "No page found for msa_id {:?} and schema_id {:?}", msa_id, schema_id),
+			Err(e) =>
+				log::error!(target: LOG_TARGET, "Error getting the page for msa_id {:?} and schema_id {:?} with {:?}", msa_id, schema_id, e),
+		}
+	}
+	log::info!(target: LOG_TARGET, "Storage migrated to version 1  read={:?}, write={:?}, bytes={:?}", reads, writes, bytes);
+	let weights = T::DbWeight::get().reads_writes(reads, writes).add_proof_size(bytes);
+	log::info!(target: LOG_TARGET, "migrate_msa_ids weights={:?}",weights);
+	weights
+}
```
Comment (saraswatpuneet) [inline pallets/stateful-storage/src/migration/v1.rs:229]: logic looks good
nit: reduce nesting but since its a one time migration

**Review by saraswatpuneet — APPROVED** [review]
lgtm

File: pallets/stateful-storage/src/migration/v1.rs (hunk 1 above)
Comment (aramikm) [reply pallets/stateful-storage/src/migration/v1.rs:229]: Yeah I was on the fence about that but since I wanted to log all the failure cases the other alternative was to use a lot of `continue` in the loop which is also not that great.
```

Comment (shannonwells) [reply pallets/stateful-storage/src/migration/v1.rs:229]: I think it's cleared up once you get down to the alternate cases, but a couple of comments would be nice.  I wonder if you have found any empty itemized pages stored.

**Review by shannonwells — APPROVED** [review]
Read through the code, looks good to go given the migration tests.

File: pallets/stateful-storage/src/migration/v1.rs (hunk 1 above)
Comment (aramikm) [reply pallets/stateful-storage/src/migration/v1.rs:229]: I couldn't find any empty itemized pages but still had to handle it just in case.

**Review by mattheworris — APPROVED** [review]
- Read through changes
- Executed `make try-runtime-upgrade-paseo-testnet`
  - Did not see observed host function errors, but did get errors scraping keys, probably network related

🚢 it!
