### PR TITLE
bugfix: eip-191 hash calculation fix

### LINKED ISSUE #2247: [Bug]: Ethereum eip-191 signatures are not working correctly
### What happened?

Valid `ecdsa` signatures signed using eip-191 and JS libraries is not getting verified correctly. The issue seems to be related to how the message hash is getting calculated.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by aramikm**
# Goal
The goal of this PR is to make sure the hash calculation for eip-191 is compatible with JS libraries.

Closes #2247 

# Discussion
- Changed eip-191 message hash calculation to match js implementation in popular Ethereum libraries

# Checklist
- [X] Unit Tests added?
- [X] Spec version incremented?

### CODE REVIEW

File: common/primitives/src/signatures.rs [hunk 1]
```diff
@@ -270,21 +274,14 @@ fn check_ethereum_signature<L: Lazy<[u8]>>(
...
 	// signature of raw payload, compatible with polkadotJs signatures
 	let hashed = sp_io::hashing::keccak_256(&msg.get());
-	if verify_signature(signature.as_ref(), &hashed, signer) {
-		return true
-	}
-
-	// frequency wrapped for Metamask compatibility
-	let frequency_wrapped =
-		eth_message_hash(&format!("<Frequency>0x{:?}</Frequency>", HexDisplay::from(&msg.get())));
-	verify_signature(&signature.as_ref(), &frequency_wrapped, signer)
```
Comment (aramikm) [inline common/primitives/src/signatures.rs:287]: Removing this custom wrapping for now. We might not need it and we will cross that bridge in future in case it was necessary.

File: common/primitives/src/signatures.rs [hunk 2]
```diff
@@ -254,10 +257,11 @@ fn check_secp256k1_signature(signature: &[u8; 65], msg: &[u8; 32], signer: &Acco
 	}
 }
 
-fn eth_message_hash(message: &str) -> [u8; 32] {
-	let prefixed = format!("{}{}{}", "\x19Ethereum Signed Message:\n", message.len(), message);
-	log::debug!(target:"ETHEREUM", "prefixed {:?}",prefixed);
-	sp_io::hashing::keccak_256(prefixed.as_bytes())
+fn eth_message_hash(message: &[u8]) -> [u8; 32] {
```
Comment (aramikm) [inline common/primitives/src/signatures.rs:260]: matches https://github.com/ethers-io/ethers.js/blob/48cdcef2925ffca4f60412697791dac268f06d0d/src.ts/hash/message.ts#L35

**Review by shannonwells — APPROVED** [review]
I don't want to block it for this because if the inputs weren't real, the signatures wouldn't validate and the accounts wouldn't decode and such, but it would be nice to know where you got the signatures and accounts from for future testing.

**Review by wilwade — APPROVED** [review]
👍

**Review by mattheworris — APPROVED** [review]
- Read through changes
🚢 it!

**Review by saraswatpuneet — APPROVED** [review]

**Review by JoeCap08055 — APPROVED** [review]
Read through code & also ECR-191. Looks good!

**Review by enddynayn — APPROVED** [review]
Great! 👍

File: common/primitives/src/signatures.rs [hunk 3]
```diff
@@ -308,14 +305,14 @@ mod tests {
...
-		let signature_raw = from_hex("0x056ca64d31251a1f20733ce2a741e2963c87a9674a35f8619b6b97210ae8c8b54c2853da1b943dd95ac3b893b37f69ca7dc38c13f8ec92a235b00ae03426505900").expect("Should convert");
+		let payload = b"test eip-191 message payload";
+		let signature_raw = from_hex("0x276dcc9c69da24dd8441ba3acc9b60d8aae0cb39f0bc5ad92c723a31bf11575031d860978280191a0a97a1f74336ca0c79a8b1b3aab013fb58a27f113b73b2081b").expect("Should convert");
 		let unified_signature = UnifiedSignature::from(ecdsa::Signature::from_raw(
 			signature_raw.try_into().expect("should convert"),
 		));
 
 		let public_key = ecdsa::Public::from_raw(
-			from_hex("0x025b107c7f38d5ac7d618e626f9fa57eec683adf373b1352cd20e5e5c684747079")
+			from_hex("0x03be5b145e12c5fb95151374ed919eb445ade57637d729dd2d73bf161d4bc10329")
```
Comment (aramikm) [inline common/primitives/src/signatures.rs:315]: compressed public key associated with the account used in metamask for signing `0x6906405649a9c73f28BB3D9bC3B647280D822025`

**Comment by aramikm** [comment]
@shannonwells added some more comments in PR. The example test is also exactly what saas team was submitting to us and added that to ensure we are compatible with them
