### PR TITLE
Display handles are whitespace trimed and collapsed

### LINKED ISSUE #1673: User handles doesn't strip leading/trailing whitespace
While leading and trailing whitespace are allowed (they are stripped before canonicalization), the length requirement is being broken by only checking before canonicalization instead of after.

image
image

### LINKED ISSUE #2148: Trim Display Handle Whitespace
While it doesn't effect lookup due to the canonical handle, Display handles should be cleaner.

- Remove all whitespace from the leading and trailing end of a display handle
     - ` this is a display handle              ` -> `this is a display handle`
- Collapse all whitespace to just one ` ` if duplicated
     - `this    is     a display        handle`   -> `this is a display handle`
     
## Notes

- Do not modify existing handles. They can remain
- Watch out for loop cost. Might be worth adding in with another loop such as ban loop for `@#`etc..

### PR DESCRIPTION
**Pull request by wilwade**
# Goal
The goal of this PR is to ensure that all new base handles (and thus the resulting display handle) have whitespace trimmed and concatenated

Closes #2148 

# Discussion

Fairly straightforward. I did benchmark against the collapse crate, and tested some with the versions here: https://stackoverflow.com/questions/71864137/whats-the-ideal-way-to-trim-extra-spaces-from-a-string

In the end this one benchmarked the fastest using a version of this:

```rust
#[cfg(test)]
mod tests {
    use super::*;
    use rand::distributions::Alphanumeric;
    use rand::distributions::DistString;
    use test::Bencher;

    #[bench]
    fn bench_one(b: &mut Bencher) {
        let mut rng = rand::thread_rng();
        b.iter(|| {
            trim_and_collapse_whitespace(
                Alphanumeric
                    .sample_string(&mut rng, 20)
                    .to_lowercase()
                    .replace("a", " ")
                    .replace("b", " ")
                    .as_str(),
            );
        });
    }
}
```

# Checklist
- [x] Updated Pallet Readme?
- [x] Design doc(s) updated?
- [x] Unit Tests added?
- [x] Spec version incremented?

### CODE REVIEW

File: pallets/handles/src/lib.rs [hunk 1]
```diff
@@ -711,8 +713,9 @@ pub mod pallet {
 			base_handle: &str,
 			suffix: HandleSuffix,
 		) -> Result<DisplayHandle, DispatchError> {
+			let base_handle_trimmed = trim_and_collapse_whitespace(base_handle);
```
Comment (wilwade) [inline pallets/handles/src/lib.rs:716]: Believe it or not, this appears to be the place that builds the display handle that is saved.

File: pallets/handles/src/handles-utils/src/converter.rs [hunk 2]
```diff
@@ -84,7 +84,7 @@ pub fn split_display_name(display_name_str: &str) -> Option<(String, HandleSuffi
 	let parts: Vec<&str> = display_name_str.split(HANDLE_DELIMITER).collect();
 	let base_handle_str = parts[0].to_string();
 	if parts.len() != 2 {
-		return None
+		return None;
```
Comment (wilwade) [inline pallets/handles/src/handles-utils/src/converter.rs:87]: My formatter really wants to have `;` at the end of the line when it is `return`

**Review by saraswatpuneet — APPROVED** [review]
clean! lgtm

File: designdocs/user-handles.md [hunk 3]
```diff
@@ -66,7 +67,7 @@ Handles```registry``` on Frequency chain.
 
 ### Handle replay attack
 
-To prevent replay attacks, the chain will require a mortality period for handles. This can be included in signed payload from user as a `expiration` field. The chain will check if the `expiration` is greater than the current block number. If not, the transaction will fail.  
+To prevent replay attacks, the chain will require a mortality period for handles. This can be included in signed payload from user as a `expiration` field. The chain will check if the `expiration` is greater than the current block number. If not, the transaction will fail.
```
Comment (mattheworris) [inline designdocs/user-handles.md:70]: nit: correct a to an, and active voice
```suggestion
To prevent replay attacks, the chain will require a mortality period for handles. This can be included in the user's signed payload as an `expiration` field. The chain will check if the `expiration` is greater than the current block number. If not, the transaction will fail.
```

File: designdocs/user-handles.md [hunk 4]
```diff
@@ -135,7 +136,7 @@ ClaimHandlePayload {
 
 ### Claim handle
 
- As a network, Frequency should allow users to choose their own handle, while the chain will generate a random numeric suffix within the range of suffixes allowed. The display handle will be the base handle with the suffix.
+ As a network, Frequency should allow users to choose their own handle, while the chain will generate a random numeric suffix within the range of suffixes allowed. The display handle will be the base handle with whitespace trimmed and concatenated with the suffix.
```
Comment (JoeCap08055) [inline designdocs/user-handles.md:139]:
```suggestion
 As a network, Frequency should allow users to choose their own handle, while the chain will generate a random numeric suffix within the range of suffixes allowed. The display handle will be the base handle with whitespace trimmed and consolidated, concatenated with the suffix.
```
